spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcits?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
    jpa:
      show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8769/eureka/
  instance:
    prefer-ip-address: true
